baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Le Poete'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
